services:
  postgres:
    container_name: panache_postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: panache
      POSTGRES_PASSWORD: panache
      POSTGRES_DB: panache
    volumes:
      - panache_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  panache_postgres_data:
