services:
  postgres:
    container_name: panache_postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: panache
      POSTGRES_PASSWORD: panache
      POSTGRES_DB: panache
    volumes:
      - panache_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    container_name: panache_minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: 'minio server /data/minio --console-address ":8900"'
    volumes:
      - panache_minio_data:/data

    ports:
      - 8900:8900
      - 9000:9000

volumes:
  panache_postgres_data:
  panache_minio_data:
